# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# Add the current directory to Python path
current_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['main.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        'geopandas',
        'shapely',
        'fiona',
        'pyogrio',
        'pyproj',
        'rtree',
        'geos',
        'gdal',
        'osgeo',
        'osgeo.gdal',
        'osgeo.ogr',
        'osgeo.osr',
        'osgeo.gdal_array',
        'osgeo.gdalconst',
        'pandas',
        'numpy',
        'xarray',
        'netCDF4',
        'cftime',
        'aiohttp',
        'multiprocessing',
        'multiprocessing.util',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.simpledialog',
        'tkinter.colorchooser',
        'webbrowser',
        'threading',
        'queue',
        'pathlib',
        'json',
        'xml.etree.ElementTree',
        'datetime',
        'functools',
        'itertools',
        'collections',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'urllib.error',
        'ssl',
        'socket',
        'select',
        'subprocess',
        'tempfile',
        'shutil',
        'zipfile',
        'gzip',
        'bz2',
        'lzma',
        'hashlib',
        'hmac',
        'base64',
        'binascii',
        'struct',
        'ctypes',
        'ctypes.wintypes',
        'msvcrt',
        'nt',
        'winreg',
        'winsound',
        '_winapi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MDA_Layers_Downloader_v1.3',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='mda_layers_downloader.ico',
    version_file=None,
)