# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# Manually collect GDAL and PROJ data files
all_datas = []
all_binaries = []

# Add PROJ data files
proj_paths = [
    os.path.join(sys.prefix, 'share', 'proj'),
    os.path.join(sys.prefix, 'Library', 'share', 'proj'),
    os.path.join(sys.prefix, 'Library', 'lib', 'python3.14', 'site-packages', 'pyproj', 'proj_data')
]

for proj_path in proj_paths:
    if os.path.exists(proj_path):
        for root, dirs, files in os.walk(proj_path):
            for file in files:
                if file.endswith(('.db', '.tif', '.tiff', '.csv', '.json')):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, proj_path)
                    all_datas.append((full_path, os.path.join('proj', rel_path)))

# Add GDAL data files
gdal_paths = [
    os.path.join(sys.prefix, 'share', 'gdal'),
    os.path.join(sys.prefix, 'Library', 'share', 'gdal'),
    os.path.join(sys.prefix, 'Library', 'lib', 'python3.14', 'site-packages', 'osgeo', 'data')
]

for gdal_path in gdal_paths:
    if os.path.exists(gdal_path):
        for root, dirs, files in os.walk(gdal_path):
            for file in files:
                if file.endswith(('.tif', '.tiff', '.csv', '.json', '.xml', '.wkt')):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, gdal_path)
                    all_datas.append((full_path, os.path.join('gdal', rel_path)))

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=all_binaries,
    datas=all_datas,
    hiddenimports=[
        'geopandas',
        'shapely',
        'shapely.geometry',
        'shapely.ops',
        'shapely.wkt',
        'shapely.wkb',
        'fiona',
        'fiona.crs',
        'fiona.transform',
        'pyogrio',
        'pyproj',
        'pyproj.crs',
        'pyproj.transformer',
        'rtree',
        'geos',
        'gdal',
        'osgeo',
        'osgeo.gdal',
        'osgeo.ogr',
        'osgeo.osr',
        'osgeo.gdal_array',
        'osgeo.gdalconst',
        'osgeo.ogr',
        'osgeo.osr',
        'pandas',
        'numpy',
        'numpy.core',
        'xarray',
        'netCDF4',
        'cftime',
        'aiohttp',
        'multiprocessing',
        'multiprocessing.util',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.simpledialog',
        'tkinter.colorchooser',
        'tkinter.filedialog',
        'webbrowser',
        'threading',
        'queue',
        'pathlib',
        'pathlib.PurePath',
        'json',
        'xml.etree.ElementTree',
        'xml.etree',
        'datetime',
        'functools',
        'itertools',
        'collections',
        'collections.abc',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'urllib.error',
        'ssl',
        'socket',
        'select',
        'subprocess',
        'tempfile',
        'shutil',
        'zipfile',
        'gzip',
        'bz2',
        'lzma',
        'hashlib',
        'hmac',
        'base64',
        'binascii',
        'struct',
        'ctypes',
        'ctypes.wintypes',
        'msvcrt',
        'nt',
        'winreg',
        'winsound',
        '_winapi',
        'sqlite3',
        'sqlite3.dbapi2',
        'pytz',
        'dateutil',
        'dateutil.parser',
        'certifi',
        'charset_normalizer',
        'urllib3',
        'urllib3.util',
        'urllib3.connection',
        'urllib3.poolmanager',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.hooks',
        'requests.models',
        'requests.sessions',
        'requests.status_codes',
        'requests.structures',
        'requests.utils',
        'setuptools',
        'setuptools._vendor',
        'setuptools._vendor.jaraco',
        'setuptools._vendor.more_itertools',
        'setuptools._vendor.packaging',
        'pkg_resources',
        'pkgutil',
        'importlib',
        'importlib.util',
        'importlib.metadata',
        'importlib.resources',
        'platform',
        'logging',
        'logging.handlers',
        'optparse',
        'getopt',
        'argparse',
        'configparser',
        'copy',
        'copyreg',
        'pickle',
        'shelve',
        'dbm',
        'dbm.ndbm',
        'dbm.gnu',
        'csv',
        're',
        'string',
        'textwrap',
        'unicodedata',
        'io',
        'codecs',
        'locale',
        'calendar',
        'time',
        'random',
        'math',
        'cmath',
        'decimal',
        'fractions',
        'numbers',
        'operator',
        'keyword',
        'ast',
        'token',
        'tokenize',
        'inspect',
        'dis',
        'linecache',
        'tracemalloc',
        'gc',
        'weakref',
        'contextlib',
        'contextvars',
        'asyncio',
        'concurrent',
        'concurrent.futures',
        'concurrent.futures.thread',
        'concurrent.futures.process',
    ],
    hookspath=[],
    hooksconfig={
        'matplotlib': {'backends': 'all'},
        'tkinter': {'force_tkinter_egl': True},
    },
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MDA_Layers_Downloader_v1.3_SingleFile',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='mda_layers_downloader.ico',
    version_file=None,
)